repos:
- repo: local
  hooks:
      - id: black
        name: black
        entry: black
        language: system
        files: "main"
        types: [ python ]

      - id: ruff
        name: ruff
        entry: ruff
        language: system
        files: "main"
        types: [ python ]

      - id: flake8
        name: flake8
        entry: flake8
        language: system
        files: "main"
        types: [ python ]
        args: ["--statistics"]

      - id: pylint
        name: pylint
        entry: pylint
        language: system
        files: "main"
        types: [ python ]
        args:
          [
              "-rn", # Only display messages
              "-sn", # Don't display the score
              "--rcfile=.pylintrc", # Link to your config file
          ]

      - id: mypy
        name: mypy
        entry: mypy
        language: system
        files: "main"
        types: [ python ]
        args:
          [
              "--strict",
              "--namespace-packages",
              "--explicit-package-bases"
          ]